### ISSUE TITLE
timeout mechanism broken in wait_for_conversion() on python2.7

### ISSUE THREAD

**Issue by sehgalrohan** [pimoroni/ads1015-python#1]
In file library/ads1015/__init__.py, line 239, timeout is set to "False" rather than a numerical value indicating the number of seconds of timeout. This causes it to timeout immediately if the first try fails.

**Comment by sehgalrohan** [comment]
(FWIW I have tested removing the line, it fixes the issue)

**Comment by Gadgetoid** [comment]
Yikes. Good spot. I think I've got a dim recollection of my thought process here and can see how this nonsense came to pass.

**Comment by Gadgetoid** [comment]
Should be fixed in 0.0.3!
