### ISSUE TITLE
i2c_addr parameter ignored

### ISSUE THREAD

**Issue by kklimek** [pimoroni/ads1015-python#4]
Shouldn't self._i2c_addr be used here?

https://github.com/pimoroni/ads1015-python/blob/193f8b24946c7be8889f6d0b2b7c5c03c4cd0790/library/ads1015/__init__.py#L43

**Comment by Gadgetoid** [comment]
Yes and no- you're right that it's been ignored, but at this point the list of possible i2c addresses should be specified and not the specific one being used.

`i2cdevice` has a `select_address` method which should be called right after setting the Device up. In this case- it's been missed!

**Comment by kklimek** [comment]
and what if device will be on different address than "possible"? http://www.ti.com/lit/ds/symlink/ads1015-q1.pdf this seems to be compatible but has 4 different addresses possible: 48, 49, 4A and 4B

**Comment by Gadgetoid** [comment]
Seems to be compatible, or *is* compatible? I'm not sure.

For better or worse, our device libraries are strongly opinionated toward supporting our breakouts and the parts we use in them. However I'm very open to pull-requests if you find a compatible part with an additional i2c address that works.
