### ISSUE TITLE
Add 0.512V to the docstring for programmable gain setting

### ISSUE THREAD

**Issue by sandyjmacdonald** [pimoroni/ads1015-python#5]
The docstring should also mention the 0.512V setting.

https://github.com/pimoroni/ads1015-python/blob/208ad105468f073c7d2d379c74f4f30108c67a87/library/ads1015/__init__.py#L173-L185

Also, should it read `+/-6.144`? rather than `+=6.144`?

**Comment by Gadgetoid** [comment]
Yes, it should read `+-6.144`!
